{% set version = "3.1.1" %}
{% set sha256 = "30c9fe2034d5da90c7b2051570dd8b9d59e05b8b9037a1c80bb088dce9c1f5d9" %}

package:
  name: nvtx-c
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/NVTX/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

test:
  commands:
    - test -e "$PREFIX"/include/nvtx3/nvToolsExt.h  # [not win]
    - if not exist "%LIBRARY_INC%"\nvtx3\nvToolsExt.h exit 1  # [win]

about:
  home: https://nvidia.github.io/NVTX/doxygen/index.html
  summary: NVIDA Tool Extension Library (NVTX) C API
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - shwina
